# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'PizzaPlaces' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.7.3'
  pod 'GoogleMaps', '~> 2.7.0'
  pod 'RxSwift', '~> 4.4.0'
  pod 'RxCocoa', '~> 4.4.0'
  pod 'RxGoogleMaps'

  target 'PizzaPlacesTests' do
    inherit! :search_paths
  end

  target 'PizzaPlacesUITests' do
    inherit! :search_paths
  end

end
